# Generated by Django 2.1.3 on 2018-12-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20181210_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.Cat1'),
        ),
        migrations.RemoveField(
            model_name='cat2',
            name='cat1',
        ),
        migrations.AddField(
            model_name='cat2',
            name='cat1',
            field=models.ManyToManyField(blank=True, to='basic.Cat1'),
        ),
    ]
