# Generated by Django 2.1.3 on 2018-12-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20181211_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.Cat1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.Cat2'),
        ),
    ]
