# Generated by Django 2.1.3 on 2018-12-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20181211_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat1',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
