# Generated by Django 2.1.3 on 2018-12-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value_full',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
