# Generated by Django 2.1.3 on 2018-12-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_auto_20181213_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
