# Generated by Django 2.1.3 on 2018-12-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_product_value_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat1',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='scaler',
            field=models.CharField(blank=True, choices=[('T', 'tera'), ('G', 'giga'), ('M', 'mega'), ('k', 'kilo'), ('-', '-'), ('m', 'mili'), ('u', 'mikro'), ('n', 'nano'), ('p', 'piko')], max_length=1, null=True),
        ),
    ]
