# Generated by Django 2.1.3 on 2018-12-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0014_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat1',
            name='params',
            field=models.ManyToManyField(blank=True, to='basic.Param'),
        ),
    ]
