# Generated by Django 2.1.3 on 2018-12-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_cat1_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_pretty',
            field=models.CharField(max_length=50),
        ),
    ]
