# Generated by Django 2.2.8 on 2019-12-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_auto_20191210_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Part',
        ),
    ]
