# Generated by Django 2.2.8 on 2019-12-10 23:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0018_delete_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manuf', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('pdf', models.CharField(max_length=200)),
                ('octo', models.CharField(max_length=200)),
                ('search', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('img_big', models.CharField(max_length=200)),
                ('img_big2', models.CharField(max_length=200)),
                ('img_big3', models.CharField(max_length=200)),
                ('img_big4', models.CharField(max_length=200)),
                ('img_small', models.CharField(max_length=200)),
                ('img_footprint', models.CharField(max_length=200)),
                ('img_symbol', models.CharField(max_length=200)),
                ('farnell_mnu', models.IntegerField()),
                ('farnell_czk', models.FloatField()),
                ('mouser_mnu', models.IntegerField()),
                ('mouser_czk', models.FloatField()),
                ('digikey_mnu', models.IntegerField()),
                ('digikey_czk', models.FloatField()),
                ('specs', jsonfield.fields.JSONField()),
            ],
        ),
    ]
