# Generated by Django 2.2.8 on 2019-12-11 23:46

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manuf', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('pdf', models.CharField(max_length=200)),
                ('octo', models.CharField(max_length=200)),
                ('search', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('img_big', models.CharField(max_length=200)),
                ('img_big2', models.CharField(max_length=200)),
                ('img_big3', models.CharField(max_length=200)),
                ('img_big4', models.CharField(max_length=200)),
                ('img_small', models.CharField(max_length=200)),
                ('img_footprint', models.CharField(max_length=200)),
                ('img_symbol', models.CharField(max_length=200)),
                ('farnell_mnu', models.IntegerField()),
                ('farnell_czk', models.FloatField()),
                ('mouser_mnu', models.IntegerField()),
                ('mouser_eur', models.FloatField()),
                ('digikey_mnu', models.IntegerField()),
                ('digikey_usd', models.FloatField()),
                ('specs', jsonfield.fields.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manuf', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('pdf', models.CharField(max_length=200)),
                ('octo', models.CharField(max_length=200)),
                ('search', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('img_big', models.CharField(max_length=200)),
                ('img_big2', models.CharField(max_length=200)),
                ('img_big3', models.CharField(max_length=200)),
                ('img_big4', models.CharField(max_length=200)),
                ('img_small', models.CharField(max_length=200)),
                ('img_footprint', models.CharField(max_length=200)),
                ('img_symbol', models.CharField(max_length=200)),
                ('farnell_mnu', models.IntegerField()),
                ('farnell_czk', models.FloatField()),
                ('mouser_mnu', models.IntegerField()),
                ('mouser_eur', models.FloatField()),
                ('digikey_mnu', models.IntegerField()),
                ('digikey_usd', models.FloatField()),
                ('specs', jsonfield.fields.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
