# Generated by Django 2.2.8 on 2019-12-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0022_auto_20191212_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritepart',
            name='digikey_mnu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='favouritepart',
            name='farnell_mnu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='favouritepart',
            name='mouser_mnu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='digikey_mnu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='farnell_mnu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='mouser_mnu',
            field=models.FloatField(),
        ),
    ]
