# Generated by Django 2.2.8 on 2019-12-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0023_auto_20191212_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritepart',
            name='digikey_mnu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='favouritepart',
            name='digikey_usd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='favouritepart',
            name='farnell_czk',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='favouritepart',
            name='farnell_mnu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='favouritepart',
            name='mouser_eur',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='favouritepart',
            name='mouser_mnu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='digikey_mnu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='digikey_usd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='farnell_czk',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='farnell_mnu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='mouser_eur',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='mouser_mnu',
            field=models.CharField(max_length=50),
        ),
    ]
