# Generated by Django 2.2.8 on 2019-12-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0024_auto_20191212_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritepart',
            name='name_enc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='favouritepart',
            name='search_enc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historypart',
            name='name_enc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historypart',
            name='search_enc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='favouritepart',
            name='manuf',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favouritepart',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favouritepart',
            name='search',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='manuf',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historypart',
            name='search',
            field=models.CharField(max_length=100),
        ),
    ]
